# 爷就要用yml！！！！！！！！！！！！！！！
spring:
  datasource:
    url: jdbc:mysql://42.192.50.23:3306/platformDB?serverTimezone=UTC&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 2002108
server:
  port: 9108
