#在application.properties/或者application.yml文件中没有添加数据库配置信息.
spring:
  datasource:
    url: 42.192.50.23:3306/test_tbl?serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 2002108
